
# Change summary
# - Generated by atom-package-generator
# - Left the generated code as-is, since the default is useful enough.

LanguageZvmRexxView = require './language-zvm-rexx-view'
{CompositeDisposable} = require 'atom'

module.exports = LanguageZvmRexx =
  languageZvmRexxView: null
  modalPanel: null
  subscriptions: null

  activate: (state) ->
    @languageZvmRexxView = new LanguageZvmRexxView(state.languageZvmRexxViewState)
    @modalPanel = atom.workspace.addModalPanel(item: @languageZvmRexxView.getElement(), visible: false)

    # Events subscribed to in atom's system can be easily cleaned up with a CompositeDisposable
    @subscriptions = new CompositeDisposable

    # Register command that toggles this view
    @subscriptions.add atom.commands.add 'atom-workspace', 'language-zvm-rexx:toggle': => @toggle()

  deactivate: ->
    @modalPanel.destroy()
    @subscriptions.dispose()
    @languageZvmRexxView.destroy()

  serialize: ->
    languageZvmRexxViewState: @languageZvmRexxView.serialize()

  toggle: ->
    console.log 'LanguageZvmRexx was toggled!'

    if @modalPanel.isVisible()
      @modalPanel.hide()
    else
      @modalPanel.show()
