
# Change summary
# - Generated by atom-package-generator
# - Left the generated code as-is, since the default is useful enough.

LanguageZvmRexxView = require '../lib/language-zvm-rexx-view'

describe "LanguageZvmRexxView", ->
  it "has one valid test", ->
    expect("life").toBe "easy"
